TOKEN="SFMyNTY.g2gDdAAAAAF3BHVzZXJtAAAACm1vbm9nb25hZGhuBgD6GkrsmQFiAAFRgA.RwThAIuE0rWtLhQupJdN6DBnthbCdPkiFD4CL3TXcLQ"

http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0013.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0018.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0023.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0025-Edit.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0032.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0034.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0040.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0057.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0058.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0066.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0069.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0074.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0079.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0081.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0083.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0097-Pano.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0116-Pano.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0125.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0126.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0130.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0131.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0143-Pano.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0157-Pano.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0164.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0165-Pano.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0177-Pano.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0198-Pano.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0206.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0208.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0212.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0214.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0220.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0221-Edit.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0222-Edit-2.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0224-Edit.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0225-Edit.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0229.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0230.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0236-Edit.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0237.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0240.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0241.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0242.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0243.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0244.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0245-Edit.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0249-Edit.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0253.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0256.jpg
http -f POST localhost:4000/api/admin/pictures Authorization:${TOKEN} files@test_images/DSC_0264.jpg

