"""Add picture orientation info

Revision ID: 2536eb45e015
Revises: d5631eb1243c
Create Date: 2022-08-27 08:55:00.436276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2536eb45e015'
down_revision = 'd5631eb1243c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('landscape', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'landscape')
    # ### end Alembic commands ###
