"""Add description on species

Revision ID: 624a908f9124
Revises: 9a4aeda4ceb6
Create Date: 2020-05-13 23:21:19.026418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624a908f9124'
down_revision = '9a4aeda4ceb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'description')
    # ### end Alembic commands ###
