"""Add nullable on threat / link

Revision ID: 9a4aeda4ceb6
Revises: f5c6b6003e70
Create Date: 2020-05-08 15:22:48.277913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4aeda4ceb6'
down_revision = 'f5c6b6003e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
