"""Add stared boolean attribute to pictures

Revision ID: d5642793d731
Revises: 624a908f9124
Create Date: 2020-08-21 10:30:45.339048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5642793d731'
down_revision = '624a908f9124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('stared', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'stared')
    # ### end Alembic commands ###
