from os import getenv, urandom, getenvb

import dotenv

dotenv.load_dotenv('./.env')

PICTURES_DIR = getenv('PICTURES_DIR', 'storage/PICTURES')
THUMBS_DIR = getenv('THUMBS_DIR', 'storage/THUMBS')
HALFRES_DIR = getenv('HALFRES_DIR', 'storage/HALFRES')
TEMP_DIR = getenv('TEMP_DIR', '/tmp/TEMP_DIR')

SECRET_KEY = getenvb(b"SECRET_KEY")
if not SECRET_KEY:
    SECRET_KEY = urandom(32)


POSTGRES_SERVER = getenv("POSTGRES_SERVER")
POSTGRES_USER = getenv("POSTGRES_USER")
POSTGRES_PASSWORD = getenv("POSTGRES_PASSWORD")
POSTGRES_DB = getenv("POSTGRES_DB")
SQLALCHEMY_DATABASE_URI = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_SERVER}/{POSTGRES_DB}"
)


SQLALCHEMY_POOL_SIZE = int(getenv('SQLALCHEMY_POOL_SIZE', 60))
SQLALCHEMY_POOL_MAX_OVERFLOW = int(
    getenv('SQLALCHEMY_POOL_MAX_OVERFLOW', 40))


SUPERUSER = getenv("SUPERUSER")
SUPERUSER_PASSWORD = getenv("SUPERUSER_PASSWORD")


BACKEND_CORS_ORIGINS = getenv('BACKEND_CORS_ORIGINS')


THUMB_SIZE = 1000, 1000
HALFRES_SIZE = 2000, 2000
